CREATE SEQUENCE sb_num
  START WITH 1
  MAXVALUE 999999
  INCREMENT BY 1
  NOCYCLE
  CACHE 20;

CREATE OR REPLACE FUNCTION sb_code
RETURN CHAR
IS
BEGIN
    RETURN concat('sb_',LPAD(n_num.nextval,4,0));
END;
/